image_width: 1920
image_height: 1080
camera_name: camera5
camera_matrix:
  rows: 3
  cols: 3
  data: [1779.290148,    0.     ,  993.673757,
            0.     , 1786.548569,  616.766130,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.468757, 0.204265, -0.007066, -0.005406, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1779.290148,    0.     ,  993.673757,    0.     ,
            0.     , 1786.548569 ,  616.766130,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]